### ISSUE TITLE
No .env file in the repo

### ISSUE THREAD

**Issue by elfico** [techulus/changes-page#33]
Hello,

Thanks for the wonderful app and I can't wait to have it running.

However, I checked the files and there is no `.env` file in the repo.

Would you be kind to include one?

Also, what tasks can be done and how can one contribute. Thanks

**Comment by elfico** [comment]
Hi @arjunkomath 
Trust you are well.
Just checking if you've seen this.

**Comment by arjunkomath** [comment]
I can’t share env file for obvious reason, it has my secrets. But you can env sample files for each app in its folder.

**Comment by elfico** [comment]
Thanks.

I wasn't asking you to share your .env lol

I assumed the sample env was a `.env` file. Thanks for pointing out where to find it.

**Comment by arjunkomath** [comment]
@elfico no worries. Also, I don’t have a public roadmap yet, if you’re interested in contributing I can add some planned work.
