### ISSUE TITLE
Issue when running the app

### ISSUE THREAD

**Issue by elfico** [techulus/changes-page#34]
When running the App, we get the following error:

Module not found: Can't resolve '@changes-page/supabase/types/page'

This happens bother locally and on Vercel

**Comment by elfico** [comment]
> That is strange, you can see the file here https://github.com/techulus/changes-page/blob/develop/packages/supabase/types/page.ts
> 
>     * Have you installed the packages using `pnpm`?
> 
>     * Have you build the libs using `pnpm build` command?

Just tried but ran into an error. `No Projects Matched filter`

The fix for the error is here: https://github.com/pnpm/pnpm/issues/5601#issuecomment-1821978764

Should I open a PR that modifies the package.json and also adds the `build` command to the Readme>

**Comment by arjunkomath** [comment]
@elfico The build command is already present in package.json

https://github.com/techulus/changes-page/blob/366c9aa2581433db6ac7dff27778c5586eb19911/package.json#L5C9-L5C11

**Comment by elfico** [comment]
> @elfico The build command is already present in package.json
> 
> https://github.com/techulus/changes-page/blob/366c9aa2581433db6ac7dff27778c5586eb19911/package.json#L5

Yes it is, but when I run it, I get the following result:

```
 changes-page@1.1.0 build C:\Users\User1\changes-page
 pnpm --filter './packages/*' -r build

No projects matched the filters in "C:\Users\User1\changes-page"
```
The fix provided in this link: https://github.com/pnpm/pnpm/issues/5601#issuecomment-1821978764 makes it build successfully.

I am not sure if this is just me or anyone else has the same problem

**Comment by arjunkomath** [comment]
Can you try upgrading to the latest pnpm version, if that doesn't fix the issue, feel free to raise a PR to fix build command.

**Comment by elfico** [comment]
I had v9.10.0 and updated to v.9.11.0 but that didn't solve the issue when using the default build command.

Raising a PR using the new command.
Thanks

**Comment by elfico** [comment]
Hi @arjunkomath 
The PR has been raised.
I can successfully build the project now, but I have encountered some other issues. 😂 

When running the `page` project, I got a 404 and this error in console

```
 [fetchRenderData] Fetch page error {
│   code: '42P01',
│   details: null,
│   hint: null,
│   message: 'relation "public.pages" does not exist'
│ }
```
I have been trying to debug it with no success. My Supabase credentials are correct. 
Can you help out here? is there an additional command I need to run?

I understand if you are busy with other projects, I am trying to get this running and see how to contribute. I am also noting down the additional steps so the readme can be improved upon.

Thanks for the good work here.

Cheers!

**Comment by elfico** [comment]
I am not very familiar with supabase, but I thought maybe the schemas and migrations are to run when I first run or build the project. Can you please confirm if this is true or not and what steps should be taken first.
Thanks.

**Comment by elfico** [comment]
I have been able to get this running after running the migrations manually.
Thanks for the wonderful tool.

I have a suggestion though.
A lot of work went into building this and it looks like you have a hosted paid version. However, I think it will be beneficial if you can move the billing aspects to a private repository from where you can deploy. 

This is because, with the current set up, it's easy for anyone to become your competitor by just creating an payment account, adding all the parameters to the .env

Just a thought.

**Comment by arjunkomath** [comment]
> I have been able to get this running after running the migrations manually. Thanks for the wonderful tool.
> 
> I have a suggestion though. A lot of work went into building this and it looks like you have a hosted paid version. However, I think it will be beneficial if you can move the billing aspects to a private repository from where you can deploy.
> 
> This is because, with the current set up, it's easy for anyone to become your competitor by just creating an payment account, adding all the parameters to the .env
> 
> Just a thought.

That’s a good suggestion, but unfortunately it’s too much effort to refactor and test billing changes, for the time being I don’t have the bandwidth to work on this.
